" DO NOT EDIT THIS FILE
" Add your own customizations in ~/.local/config/vim_runtime/my_configs.vim

set runtimepath+=~/.local/config/vim_runtime

source ~/.local/config/vim_runtime/vimrcs/basic.vim
source ~/.local/config/vim_runtime/vimrcs/filetypes.vim
source ~/.local/config/vim_runtime/vimrcs/plugins_config.vim
source ~/.local/config/vim_runtime/vimrcs/extended.vim
try
  source ~/.local/config/vim_runtime/my_configs.vim
catch
endtry
